apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-prod
  template:
    metadata:
      labels:
        app: flask-prod
    spec:
      containers:
        - name: flask-prod
          image: docker.io/seymaca/myapp-py:21
          ports:
            - containerPort: 80
