apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-prod-ingress
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
    - host: app.mine.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-prod
                port:
                  number: 80
