apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16, 127.0.0.1/32, 10.0.0.0/8"
spec:
  ingressClassName: nginx
  rules:
    - host: app.mine.com
      http:
        paths:
          - path: /api/v.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flask-dev
                port:
                  number: 80
