apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-dev
spec:
  ingressClassName: nginx
  rules:
    - host: app-dev.mine.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-dev
                port:
                  number: 80
